# NAS dataset specific configuration - for now do not change!
num_channels: 64 
mono_stereo: 1
address_size: 2
timestamp_size: 4
ts_tick: 0.01
bin_size: 20000
on_off_both: 1
reset_timestamp: True
verbose: True