dataset:
  dir: /net/storage/pr3/plgrid/plgg_dvs_phd/Audio/dataset_aedat_w_delays_parallel_32ch
  version: commands
  num_channels: 32
  polarity: false
  stereo: false
  cochlea: left
  channel_radius: 5
  low_time_radius: 0
  high_time_radius: 5000
  time_window: 1000000
  skip_channels: 1
  features_aggregation: global
  use_filtration: true
  div_factor: 8
  weight: 32
  thresholds:
  - 64
  - 63
  - 61
  - 60
  - 59
  - 57
  - 56
  - 55
  - 54
  - 52
  - 51
  - 50
  - 49
  - 48
  - 47
  - 46
  - 45
  - 44
  - 43
  - 42
  - 41
  - 40
  - 39
  - 38
  - 37
  - 37
  - 36
  - 35
  - 34
  - 33
  - 33
  - 32
  threshold_method: exponential
  start_threshold: 64
  end_threshold: 32
  sharpness: 1.0
  bin_width: 0.01
  cooldown_steps: 3
  mean_scale: 1.0
  std_scale: 0.5
  low_percentage: 0.7
  gausian_kernel_size: 7
nas:
  num_channels: 32
  mono_stereo: 1
  address_size: 2
  timestamp_size: 4
  ts_tick: 0.01
  bin_size: 20000
  on_off_both: 1
  reset_timestamp: true
  verbose: true
model:
  features: 2
  num_classes: 11
  conv_channels:
  - 72
  - 72
  - 72
  - 72
  conv_bits:
  - 8
  - 8
  - 8
  - 8
  stem_channels: 72
  stem_bits: 8
  rnn_channels: 72
  rnn_bits: 8
  cls_linear_channels: 72
  cls_linear_bits: 8
  conf_linear_channels: 72
  conf_linear_bits: 8
  global_pooling: max
