# --- Imports ---
import os
import sys
import time
import random
import struct
import threading
from collections import deque
import ok          # OpalKelly FrontPanel API - communication with the FPGA (USB)

# --- Project paths ---
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
# Bitstream file generated by Vivado, loaded onto the FPGA
BIT_FILE = os.path.join(REPO_ROOT, "HW", "vivado", "kws", "kws_system.runs", "impl_1", "ok_top_wrapper.bit")

# List of words recognized by the model - order matches the class indices returned by the FPGA
WORDS_COMM = [
    "yes", "no", "up", "down", "left",
    "right", "on", "off", "stop", "go", "unknown"
]

# --- Continuous mode parameters ---
BYTES_PER_FRAME = 16               # size of a single frame (4x uint32)
CONFIDENCE_THRESHOLD = 190         # confidence threshold (0-255), below which a frame is rejected as unreliable
NUM_FRAMES = 100                   # Read from FIFO each time

# --- Initialize the connection to the FPGA via FrontPanel ---
# We do this entirely BEFORE touching pygame: pygame.init() fires up
# the joystick/HID subsystem in SDL, which enumerates USB devices via
# libusb/hidraw - if that happens while FrontPanel is opening/flashing the FPGA
# (also libusb), it can segfault both libraries at once.
devices = ok.FrontPanelDevices()
dev = devices.Open("")     # opens the first detected OpalKelly device

if dev is None:
    print("Device could not be opened")
    sys.exit(1)

# Load the bitstream (FPGA configuration) - after this step the chip starts operating per the synthesized design
cfg_result = dev.ConfigureFPGA(BIT_FILE)
if cfg_result != 0:
    print(f"FPGA configuration failed, error code {cfg_result}")
    sys.exit(1)
print("FPGA configured successfully.")

# Handle to the FrontPanel data port - used to control WireIn/WireOut and read PipeOut
dp = dev.GetFPGADataPortClassic()
if dp is None:
    print("Failed to get FPGA Data Port.")
    sys.exit(1)

print(dp)

# Only now do we import and initialize pygame (display + font only -
# no joystick/audio, which we don't use) - FrontPanel already has the device
# open and configured, so there's no more risk of a libusb conflict.
import pygame
pygame.display.init()
pygame.font.init()


def reset_pipeline():
    # Reset pulse on WireIn 0x00 (bit0: 0 -> 1 -> 0) - zeroes the inference pipeline on the FPGA
    dp.SetWireInValue(0x00, 1, 1)
    dp.UpdateWireIns()
    time.sleep(0.01)
    dp.SetWireInValue(0x00, 0, 1)
    dp.UpdateWireIns()
    time.sleep(0.01)


def arm_pipeline():
    # Set WireIn 0x01 (bit0 = 1) - arms the pipeline. In continuous mode this stays
    # set once at startup and remains active - audio is fed continuously by the microphone
    # connected directly to the ADC input, there's no .wav file playback
    dp.SetWireInValue(0x01, 1, 1)
    dp.UpdateWireIns()
    time.sleep(0.01)


def disarm_pipeline():
    # Disarm (bit0 = 0) - called once, when the program shuts down
    dp.SetWireInValue(0x01, 0, 1)
    dp.UpdateWireIns()
    time.sleep(0.01)


def read_frame_batch(no_frames):
    # Read one batch of no_frames frames from PipeOut 0xA0
    read_size = no_frames * BYTES_PER_FRAME
    buf = bytearray(read_size)
    dp.ReadFromPipeOut(0xA0, buf)

    captured_frames = []

    # Decode the raw bytes frame by frame (same format as in kws_PWZ.py)
    for i in range(0, read_size, BYTES_PER_FRAME):
        chunk = buf[i:i + BYTES_PER_FRAME]
        word1, word2, word3, word4 = struct.unpack('<IIII', chunk)

        # An all-zero frame = no new data - skip it
        if word1 == 0 and word2 == 0 and word3 == 0 and word4 == 0:
            continue

        # The lowest byte of word4 is the confidence level of this frame's classification result
        confidence = word4 & 0xFF

        # The remaining bytes (11 x 8-bit result) are the raw scores for the 11 WORDS_COMM classes,
        # packed sequentially into word4 (upper bytes), word3, word2
        class_scores = [
            (word4 >> 8) & 0xFF,
            (word4 >> 16) & 0xFF,
            (word4 >> 24) & 0xFF,
            word3 & 0xFF,
            (word3 >> 8) & 0xFF,
            (word3 >> 16) & 0xFF,
            (word3 >> 24) & 0xFF,
            word2 & 0xFF,
            (word2 >> 8) & 0xFF,
            (word2 >> 16) & 0xFF,
            (word2 >> 24) & 0xFF
        ]

        class_scores[10] = class_scores[10] - 50
        captured_frames.append({
            "confidence": confidence,
            "scores": class_scores
        })
    return captured_frames


def classify_batch(frames, confidence_threshold=CONFIDENCE_THRESHOLD):
    # Filter out low-confidence frames - only "reliable" frames count toward the result
    high_conf_frames = [f for f in frames if f["confidence"] > confidence_threshold]

    if len(high_conf_frames) == 0:
        return None

    # Average the scores over all reliable frames for each of the 11 classes
    avg_scores = [0] * 11
    for frame in high_conf_frames:
        for class_idx in range(11):
            avg_scores[class_idx] += frame["scores"][class_idx]
    avg_scores = [score / len(high_conf_frames) for score in avg_scores]

    # Rank classes by averaged score, descending -> take the top three.
    # Additionally normalize to "confidence" 0-100% (only for the GUI bars).
    total = sum(max(s, 0.0) for s in avg_scores) or 1.0
    ranked_classes = sorted(range(11), key=lambda i: avg_scores[i], reverse=True)
    ranked = [(WORDS_COMM[i], 100.0 * max(avg_scores[i], 0.0) / total) for i in ranked_classes]

    top_1 = WORDS_COMM[ranked_classes[0]]
    top_2 = WORDS_COMM[ranked_classes[1]]
    top_3 = WORDS_COMM[ranked_classes[2]]

    return top_1, top_2, top_3, len(high_conf_frames), ranked


# --- Thread listening for the Enter key, to stop the continuous loop ---
stop_event = threading.Event()


def wait_for_stop_key():
    input()  # blocks until Enter is pressed
    stop_event.set()


listener_thread = threading.Thread(target=wait_for_stop_key, daemon=True)
listener_thread.start()


# ==========================================================================
# Game: Voice Maze - collect coins, avoid mines, control with your voice
# ==========================================================================
COLS, ROWS = 7, 5
# CELL, BOARD_W/H, MARGIN, SIDEBAR_W and WIN_W/H are computed further down
# (when the window is created) based on the screen resolution, so the window is
# fullscreen and the board and fonts are as large as possible - the game grid (COLS x ROWS, WALLS) stays unchanged.

# Colors
BG = (18, 20, 28)
PANEL = (28, 32, 44)
GRID_BG = (24, 27, 37)
GRID_LINE = (40, 45, 60)
WALL = (70, 78, 100)
PLAYER = (86, 210, 150)
COIN = (250, 200, 70)
MINE = (230, 90, 90)
TEXT = (235, 238, 245)
SUBTEXT = (150, 158, 176)
ACCENT = (110, 170, 255)
BAR_BG = (48, 53, 70)

WALLS = {
    (2, 1), (2, 2), (2, 3),
    (4, 0), (4, 1), (4, 3), (4, 4),
}

STATE_MENU = "menu"
STATE_PLAYING = "playing"
STATE_PAUSED = "paused"
STATE_WIN = "win"
STATE_LOSE = "lose"


class Game:
    def __init__(self):
        self.state = STATE_MENU
        self.score = 0
        self.round_start_time = None
        self.elapsed = 0.0
        self.last_command = None
        self.last_command_time = 0.0
        self.player = (1, 1)
        self.coins = set()
        self.mines = set()
        self._new_layout()

    def _free_cells(self):
        return [
            (c, r) for c in range(COLS) for r in range(ROWS)
            if (c, r) not in WALLS
        ]

    def _reachable_from(self, start, blocked):
        # BFS over the grid, avoiding walls and the given (blocked) cells -
        # used to check that the mines don't cut the player off from the coins.
        seen = {start}
        queue = deque([start])
        while queue:
            x, y = queue.popleft()
            for dx, dy in ((0, -1), (0, 1), (-1, 0), (1, 0)):
                nxt = (x + dx, y + dy)
                nx, ny = nxt
                if not (0 <= nx < COLS and 0 <= ny < ROWS):
                    continue
                if nxt in WALLS or nxt in blocked or nxt in seen:
                    continue
                seen.add(nxt)
                queue.append(nxt)
        return seen

    def _new_layout(self):
        start = (1, 1)
        free = [c for c in self._free_cells() if c != start]
        num_mines, num_coins = 3, 5

        # We randomize the mine layout, but only accept it if afterward the
        # player can still (avoiding the mines) reach at least as many free
        # cells as there are supposed to be coins - otherwise the mines could
        # block the only passage to part of the board.
        for _ in range(200):
            random.shuffle(free)
            mines = set(free[:num_mines])
            reachable = self._reachable_from(start, mines)
            candidates = [c for c in reachable if c not in mines]
            if len(candidates) >= num_coins:
                self.mines = mines
                random.shuffle(candidates)
                self.coins = set(candidates[:num_coins])
                return

        # Fallback (shouldn't happen at this board size):
        # no mines, coins only on cells reachable from the starting position.
        self.mines = set()
        reachable = list(self._reachable_from(start, set()))
        random.shuffle(reachable)
        self.coins = set(reachable[:num_coins])

    def reset_round(self):
        self.player = (1, 1)
        self.score = 0
        self._new_layout()
        self.round_start_time = time.time()
        self.elapsed = 0.0

    def handle_command(self, word):
        now = time.time()
        self.last_command = word
        self.last_command_time = now

        if self.state == STATE_MENU:
            if word == "go":
                self.state = STATE_PLAYING
                self.reset_round()
            return

        if self.state == STATE_PAUSED:
            if word == "go":
                self.state = STATE_PLAYING
            return

        if self.state == STATE_PLAYING:
            if word == "stop":
                self.state = STATE_PAUSED
                return
            if word in ("up", "down", "left", "right"):
                self._move(word)
            return

        if self.state in (STATE_WIN, STATE_LOSE):
            if word == "yes":
                self.state = STATE_PLAYING
                self.reset_round()
            elif word == "no":
                pygame.event.post(pygame.event.Event(pygame.QUIT))
            return

    def _move(self, direction):
        dx, dy = {"up": (0, -1), "down": (0, 1), "left": (-1, 0), "right": (1, 0)}[direction]
        x, y = self.player
        nx, ny = x + dx, y + dy
        if not (0 <= nx < COLS and 0 <= ny < ROWS):
            return
        if (nx, ny) in WALLS:
            return
        self.player = (nx, ny)

        if self.player in self.mines:
            self.state = STATE_LOSE
            return
        if self.player in self.coins:
            self.coins.discard(self.player)
            self.score += 10
            if not self.coins:
                self.state = STATE_WIN

    def keyboard_event(self, key):
        mapping = {
            pygame.K_UP: "up", pygame.K_DOWN: "down",
            pygame.K_LEFT: "left", pygame.K_RIGHT: "right",
            pygame.K_RETURN: "go", pygame.K_BACKSPACE: "stop",
            pygame.K_y: "yes", pygame.K_n: "no",
        }
        word = mapping.get(key)
        if word:
            self.handle_command(word)

    def update(self):
        if self.state == STATE_PLAYING and self.round_start_time:
            self.elapsed = time.time() - self.round_start_time


# ==========================================================================
# GUI drawing
# ==========================================================================
def draw_board(surface, game, board_origin):
    ox, oy = board_origin
    board_rect = pygame.Rect(ox, oy, BOARD_W, BOARD_H)
    pygame.draw.rect(surface, GRID_BG, board_rect, border_radius=10)

    for c in range(COLS + 1):
        x = ox + c * CELL
        pygame.draw.line(surface, GRID_LINE, (x, oy), (x, oy + BOARD_H))
    for r in range(ROWS + 1):
        y = oy + r * CELL
        pygame.draw.line(surface, GRID_LINE, (ox, y), (ox + BOARD_W, y))

    for (c, r) in WALLS:
        rect = pygame.Rect(ox + c * CELL + 2, oy + r * CELL + 2, CELL - 4, CELL - 4)
        pygame.draw.rect(surface, WALL, rect, border_radius=6)

    for (c, r) in game.mines:
        cx, cy = ox + c * CELL + CELL // 2, oy + r * CELL + CELL // 2
        pygame.draw.circle(surface, MINE, (cx, cy), CELL // 4)
        pygame.draw.circle(surface, (60, 20, 20), (cx, cy), CELL // 4, 2)

    for (c, r) in game.coins:
        cx, cy = ox + c * CELL + CELL // 2, oy + r * CELL + CELL // 2
        pygame.draw.circle(surface, COIN, (cx, cy), CELL // 5)

    px, py = game.player
    prect = pygame.Rect(ox + px * CELL + 6, oy + py * CELL + 6, CELL - 12, CELL - 12)
    pygame.draw.rect(surface, PLAYER, prect, border_radius=8)

    pygame.draw.rect(surface, GRID_LINE, board_rect, 2, border_radius=10)


def draw_bar(surface, font_small, x, y, w, h, label, value_pct, color):
    pygame.draw.rect(surface, BAR_BG, (x, y, w, h), border_radius=6)
    fill_w = max(2, int(w * min(value_pct, 100) / 100))
    pygame.draw.rect(surface, color, (x, y, fill_w, h), border_radius=6)
    txt = font_small.render(f"{label.upper():<8} {value_pct:5.1f}%", True, TEXT)
    surface.blit(txt, (x + 8, y + h // 2 - txt.get_height() // 2))


def draw_sidebar(surface, fonts, game, top3, origin, size):
    font_title, font, font_small, font_big = fonts
    x, y = origin
    w, h = size
    pygame.draw.rect(surface, PANEL, (x, y, w, h), border_radius=12)

    pad = max(16, w // 24)
    gap = max(6, font_small.get_linesize() // 4)
    cx = x + pad
    cy = y + pad

    def line(f, text, color, extra_gap=0):
        nonlocal cy
        surf = f.render(text, True, color)
        surface.blit(surf, (cx, cy))
        cy += f.get_linesize() + extra_gap

    line(font_title, "Voice Maze", ACCENT, gap * 2)
    line(font_small, "CONNECTED TO FPGA", (110, 220, 140), gap * 2)

    line(font, "Top 3 predictions:", SUBTEXT, gap)
    bar_colors = [ACCENT, (150, 130, 220), (90, 100, 130)]
    bar_h = font_small.get_linesize() + 14
    for i, (word, pct) in enumerate(top3):
        draw_bar(surface, font_small, cx, cy, w - 2 * pad, bar_h, word, pct, bar_colors[i])
        cy += bar_h + gap
    cy += gap * 2

    last_cmd = game.last_command or "-"
    age = time.time() - game.last_command_time if game.last_command_time else 999
    fresh = age < 0.6
    cmd_color = (110, 220, 140) if fresh else SUBTEXT
    line(font, "Last command:", SUBTEXT)
    line(font_big, last_cmd.upper(), cmd_color, gap * 2)

    line(font, f"Score: {game.score}", TEXT)
    line(font, f"Coins left: {len(game.coins)}", TEXT)
    line(font, f"Time: {game.elapsed:5.1f} s", TEXT, gap * 2)

    help_lines = [
        "GO - start/resume   STOP - pause",
        "UP DOWN LEFT RIGHT - move",
        "YES - restart (after end)",
        "NO - quit",
        "",
        "Keyboard: arrows, Enter,",
        "Backspace, Y, N, Esc",
    ]
    line(font_small, "Keywords:", SUBTEXT, gap // 2)
    for text in help_lines:
        line(font_small, text, SUBTEXT)


def draw_overlay(surface, fonts, win_size, text, subtext, color):
    font_title, font, font_small, font_big = fonts
    w, h = win_size
    overlay = pygame.Surface((w, h), pygame.SRCALPHA)
    overlay.fill((10, 12, 18, 190))
    surface.blit(overlay, (0, 0))

    title = font_title.render(text, True, color)
    gap = font_title.get_linesize() // 2
    if subtext:
        sub = font.render(subtext, True, TEXT)
        surface.blit(title, title.get_rect(center=(w // 2, h // 2 - gap)))
        surface.blit(sub, sub.get_rect(center=(w // 2, h // 2 + gap)))
    else:
        surface.blit(title, title.get_rect(center=(w // 2, h // 2)))


pygame.display.set_caption("Voice Maze")

# Fullscreen at the monitor's native resolution.
info = pygame.display.Info()
screen = pygame.display.set_mode((info.current_w, info.current_h), pygame.FULLSCREEN)
WIN_W, WIN_H = screen.get_size()
clock = pygame.time.Clock()

# Layout (margins, sidebar, header, cell size) computed from the screen
# resolution - the game grid (COLS x ROWS) stays unchanged, we just
# draw it much larger, so that everything (including the instructions) is legible.
MARGIN = max(20, WIN_H // 40)
SIDEBAR_W = max(420, WIN_W // 4)
HEADER_H = max(90, WIN_H // 9)

avail_w = WIN_W - SIDEBAR_W - MARGIN * 3
avail_h = WIN_H - MARGIN * 2 - HEADER_H
CELL = max(20, min(avail_w // COLS, avail_h // ROWS, 160))
BOARD_W = CELL * COLS
BOARD_H = CELL * ROWS

font_title = pygame.font.SysFont("arial", max(34, WIN_H // 20), bold=True)
font = pygame.font.SysFont("arial", max(20, WIN_H // 34))
font_small = pygame.font.SysFont("arial", max(16, WIN_H // 42))
font_big = pygame.font.SysFont("arial", max(26, WIN_H // 26), bold=True)
fonts = (font_title, font, font_small, font_big)

game = Game()
top3 = [("-", 0.0), ("-", 0.0), ("-", 0.0)]

board_origin = (MARGIN, MARGIN + HEADER_H)
sidebar_origin = (WIN_W - SIDEBAR_W - MARGIN, MARGIN)
sidebar_size = (SIDEBAR_W, WIN_H - 2 * MARGIN)

print("\n=======================================================")
print(" KWS Demo - Voice Maze - audio z mikrofonu (bez odtwarzania plików)")
print(" Nacisnij Enter (w konsoli) lub zamknij okno, aby zatrzymac.")
print("=======================================================\n")

# --- Main continuous loop ---
# Reset and arming of the pipeline are done once at startup - after that the FPGA
# stays armed the whole time and in the loop we only read the next batches of frames
reset_pipeline()
arm_pipeline()

iteration = 0
running = True
try:
    while running and not stop_event.is_set():
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key in (pygame.K_ESCAPE, pygame.K_q):
                    running = False
                else:
                    game.keyboard_event(event.key)

        dp.UpdateWireOuts()
        fifo_cnt = dp.GetWireOutValue(0x20)
        if (fifo_cnt >= NUM_FRAMES):
            frames = read_frame_batch(int(fifo_cnt/4))
            result = classify_batch(frames)

            if result is not None:
                top_1, top_2, top_3, valid_count, ranked = result
                print(f"[{iteration}] TOP1: {top_1:<8} | TOP2: {top_2:<8} | TOP3: {top_3:<8} "
                      f"(wiarygodne klatki: {valid_count}/{len(frames)})")

                # --- Update the game based on the recognized word ---
                top3 = ranked[:3]
                if top_1 != "unknown":
                    game.handle_command(top_1)

            iteration += 1
            if (iteration % 10 == 0):
                disarm_pipeline()
                reset_pipeline()
                arm_pipeline()
            # if (iteration % 100 == 0):
            #     running = False
            time.sleep(0.1)

        game.update()

        screen.fill(BG)
        header = font_title.render("Keyword Spotting System - DEMO", True, TEXT)
        screen.blit(header, (MARGIN, MARGIN // 2))

        draw_board(screen, game, board_origin)
        draw_sidebar(screen, fonts, game, top3, sidebar_origin, sidebar_size)

        if game.state == STATE_MENU:
            draw_overlay(screen, fonts, (WIN_W, WIN_H), "Say GO to start",
                         "Collect all coins, avoid the mines", ACCENT)
        elif game.state == STATE_PAUSED:
            draw_overlay(screen, fonts, (WIN_W, WIN_H), "PAUSED",
                         "Say GO to resume", (200, 200, 90))
        elif game.state == STATE_WIN:
            draw_overlay(screen, fonts, (WIN_W, WIN_H), "YOU WIN!",
                         f"Score: {game.score}  |  YES - play again, NO - quit", (110, 220, 140))
        elif game.state == STATE_LOSE:
            draw_overlay(screen, fonts, (WIN_W, WIN_H), "YOU HIT A MINE",
                         f"Score: {game.score}  |  YES - play again, NO - quit", MINE)

        pygame.display.flip()
        clock.tick(60)
finally:
    # Cleanup: disarm the pipeline when the program shuts down
    disarm_pipeline()
    pygame.quit()
    print("\nZatrzymano tryb ciagly.")
