# --- Imports ---
import os
import sys
import time
import struct
import threading
import ok          # OpalKelly FrontPanel API - communication with the FPGA (USB)

# --- Project paths ---
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
# Bitstream file generated by Vivado, loaded onto the FPGA
BIT_FILE = os.path.join(REPO_ROOT, "HW", "vivado", "kws", "kws_system.runs", "impl_1", "ok_top_wrapper.bit")

# List of words recognized by the model - order matches the class indices returned by the FPGA
WORDS_COMM = [
    "yes", "no", "up", "down", "left",
    "right", "on", "off", "stop", "go", "unknown"
]

# --- Continuous mode parameters ---
BYTES_PER_FRAME = 16               # size of a single frame (4x uint32)
CONFIDENCE_THRESHOLD = 190         # confidence threshold (0-255), below which a frame is rejected as unreliable
NUM_FRAMES = 100                   # Read from FIFO each time

# --- Initialize the connection to the FPGA via FrontPanel ---
devices = ok.FrontPanelDevices()
dev = devices.Open("")     # opens the first detected OpalKelly device

if dev is None:
    print("Device could not be opened")
    sys.exit(1)

# Load the bitstream (FPGA configuration) - after this step the chip starts operating per the synthesized design
cfg_result = dev.ConfigureFPGA(BIT_FILE)
if cfg_result != 0:
    print(f"FPGA configuration failed, error code {cfg_result}")
    sys.exit(1)
print("FPGA configured successfully.")

# Handle to the FrontPanel data port - used to control WireIn/WireOut and read PipeOut
dp = dev.GetFPGADataPortClassic()
if dp is None:
    print("Failed to get FPGA Data Port.")
    sys.exit(1)

print(dp)

def reset_pipeline():
    # Reset pulse on WireIn 0x00 (bit0: 0 -> 1 -> 0) - zeroes the inference pipeline on the FPGA
    dp.SetWireInValue(0x00, 1, 1)
    dp.UpdateWireIns()
    time.sleep(0.01)
    dp.SetWireInValue(0x00, 0, 1)
    dp.UpdateWireIns()
    time.sleep(0.01)


def arm_pipeline():
    # Set WireIn 0x01 (bit0 = 1) - arms the pipeline. In continuous mode this stays
    # set once at startup and remains active - audio is fed continuously by the microphone
    # connected directly to the ADC input, there's no .wav file playback
    dp.SetWireInValue(0x01, 1, 1)
    dp.UpdateWireIns()
    time.sleep(0.01)


def disarm_pipeline():
    # Disarm (bit0 = 0) - called once, when the program shuts down
    dp.SetWireInValue(0x01, 0, 1)
    dp.UpdateWireIns()
    time.sleep(0.01)


def read_frame_batch(no_frames):
    # Read one batch of no_frames frames from PipeOut 0xA0
    read_size = no_frames * BYTES_PER_FRAME
    buf = bytearray(read_size)
    dp.ReadFromPipeOut(0xA0, buf)

    captured_frames = []

    # Decode the raw bytes frame by frame (same format as in kws_PWZ.py)
    for i in range(0, read_size, BYTES_PER_FRAME):
        chunk = buf[i:i + BYTES_PER_FRAME]
        word1, word2, word3, word4 = struct.unpack('<IIII', chunk)

        # An all-zero frame = no new data - skip it
        if word1 == 0 and word2 == 0 and word3 == 0 and word4 == 0:
            continue

        # The lowest byte of word4 is the confidence level of this frame's classification result
        confidence = word4 & 0xFF

        # The remaining bytes (11 x 8-bit result) are the raw scores for the 11 WORDS_COMM classes,
        # packed sequentially into word4 (upper bytes), word3, word2
        class_scores = [
            (word4 >> 8) & 0xFF,
            (word4 >> 16) & 0xFF,
            (word4 >> 24) & 0xFF,
            word3 & 0xFF,
            (word3 >> 8) & 0xFF,
            (word3 >> 16) & 0xFF,
            (word3 >> 24) & 0xFF,
            word2 & 0xFF,
            (word2 >> 8) & 0xFF,
            (word2 >> 16) & 0xFF,
            (word2 >> 24) & 0xFF
        ]

        #print(str(class_scores) + " | " + str(confidence))
        class_scores[10] = class_scores[10] - 50
        captured_frames.append({
            "confidence": confidence,
            "scores": class_scores
        })
        #print(class_scores)
    return captured_frames


def classify_batch(frames, confidence_threshold=CONFIDENCE_THRESHOLD):
    # Filter out low-confidence frames - only "reliable" frames count toward the result
    high_conf_frames = [f for f in frames if f["confidence"] > confidence_threshold]

    if len(high_conf_frames) == 0:
        return None

    # Average the scores over all reliable frames for each of the 11 classes
    avg_scores = [0] * 11
    for frame in high_conf_frames:
        for class_idx in range(11):
            avg_scores[class_idx] += frame["scores"][class_idx]
    avg_scores = [score / len(high_conf_frames) for score in avg_scores]
    print(avg_scores)
    # Rank classes by averaged score, descending -> take the top three
    ranked_classes = sorted(range(11), key=lambda i: avg_scores[i], reverse=True)
    top_1 = WORDS_COMM[ranked_classes[0]]
    top_2 = WORDS_COMM[ranked_classes[1]]
    top_3 = WORDS_COMM[ranked_classes[2]]

    return top_1, top_2, top_3, len(high_conf_frames)


# --- Thread listening for the Enter key, to stop the continuous loop ---
stop_event = threading.Event()


def wait_for_stop_key():
    input()  # blocks until Enter is pressed
    stop_event.set()


listener_thread = threading.Thread(target=wait_for_stop_key, daemon=True)
listener_thread.start()

print("\n=======================================================")
print(" KWS Continuous Mode - audio z mikrofonu (bez odtwarzania plików)")
print(" Nacisnij Enter, aby zatrzymac.")
print("=======================================================\n")

# --- Main continuous loop ---
# Reset and arming of the pipeline are done once at startup - after that the FPGA
# stays armed the whole time and in the loop we only read the next batches of frames
reset_pipeline()
arm_pipeline()

iteration = 0
try:
    while not stop_event.is_set():

        dp.UpdateWireOuts()
        fifo_cnt = dp.GetWireOutValue(0x20)
        if (fifo_cnt >= NUM_FRAMES): 
            # print(fifo_cnt)
            frames = read_frame_batch(int(fifo_cnt/4))
            result = classify_batch(frames)

            if result is not None:
                top_1, top_2, top_3, valid_count = result
                print(f"[{iteration}] TOP1: {top_1:<8} | TOP2: {top_2:<8} | TOP3: {top_3:<8} "
                      f"(wiarygodne klatki: {valid_count}/{len(frames)})")

            iteration += 1
            if (iteration % 10 == 0):
                disarm_pipeline()
                reset_pipeline()
                arm_pipeline()
            if (iteration % 100 == 0):
                exit()
finally:
    # Cleanup: disarm the pipeline when the program shuts down
    disarm_pipeline()
    print("\nZatrzymano tryb ciagly.")
